---
layout: redirected
sitemap: false
permalink: https://awgutierrez.github.io/
redirect_to:  https://armando-w-gutierrez.netlify.app/

theme: jekyll-theme-cayman
title: Armando W. Gutiérrez
description: postdoctoral researcher in mathematics
tagline: postdoctoral researcher at Aalto University
url: https://awgutierrez.github.io/
author: Armando W. Gutiérrez
google-site-verification: google84436875eb5f381d.html
social:
  name: Armando W. Gutiérrez
  links:
    - https://scholar.google.fi/citations?hl=en&user=xVvnb7sAAAAJ
    - https://www.researchgate.net/profile/Armando_Gutierrez5
    - https://orcid.org/0000-0001-5010-7103
markdown: kramdown
google_analytics: UA-142698973-2
kramdown:
  math_engine: katex
  syntax_highlighter: rouge
---
