theme: jekyll-theme-cayman
title: Armando W. Gutiérrez
markdown: kramdown

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_CHTML"></script>
