theme: jekyll-theme-modernist
title: Armando W. Gutiérrez
show_downloads: false
github:
  repository_url: https://github.com/awgutierrez/awgutierrez.github.io
  another_url: https://sites.google.com/view/armando-w-gutierrez/research
