---
layout: redirected
sitemap: false
permalink: https://awgutierrez.github.io/
redirect_to:  https://armando-w-gutierrez.netlify.app/

gems:
  - jekyll-redirect-from
  
theme: jekyll-theme-cayman
title: Armando W. Gutiérrez
description: postdoctoral researcher in mathematics
tagline: postdoctoral researcher
url: https://awgutierrez.github.io/
author: Armando W. Gutiérrez
google-site-verification: 
social:
  name: Armando W. Gutiérrez
  links:
    - https://scholar.google.fi/citations?user=hnBZJrQAAAAJ&hl=en
markdown: kramdown
google_analytics: 
kramdown:
  math_engine: katex
  syntax_highlighter: rouge
---
